# Generated by Django 3.1.1 on 2020-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200912_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresponse',
            name='gradelevel',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='keyphrases',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='wpm',
            field=models.IntegerField(default=-1),
        ),
    ]
