# Generated by Django 3.1.1 on 2020-09-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200912_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresponse',
            name='um',
            field=models.TextField(default='N/A'),
        ),
    ]
